### ISSUE TITLE
The Game NOT WORK after open

### ISSUE THREAD

**Issue by WAME45455** [RSDKModding/RSDKv3-Decompilation#243]
### Expected Behavior

OPEN THE GAME

### Actual Behavior

When I open the program it instantly closes

### Steps to Reproduce

1. open the folder of the game, 2. open the game, 3. close instantly

### Screenshots

I don't have a screenshot because it closes instantly

### Log File

The log.txt file tells me this:

Couldn't load file 'Data/Scripts/ByteCode/GlobalCode.bin'
Loaded File 'Data/Scripts/ByteCode/GS000.bin'
Loaded File 'Data/Game/GameConfig.bin'
Couldn't load file 'Data/Game/Game.xml'
Couldn't load file 'Data/Game/Game.xml'
Couldn't load file 'Data/Game/Game.xml'
Couldn't load file 'Data/Game/Game.xml'
Couldn't load file 'Data/Game/Game.xml'
Couldn't load file 'Data/Game/Game.xml'
glew init error:
Missing GL version

### Decompilation Version

the version is 1.3.2

### Game Version

Blit Release (Steam/XBOX 360/PS3)

### Game Revision

I don't know

### Script Platform Type

Standard

### Renderer Type

Software Renderer

### Platform

Windows

### Additional Comments

IM SPANISH

**Comment by Mefiresu** [comment]
> glew init error:
Missing GL version

Sounds like a GPU issue, try updating your GPU driver

**Comment by MegAmi24** [comment]
Closing due to likely being a GPU issue as described above.
